filter:
    paths:
        - 'src/*'
checks:
    php:
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true

coding_style:
    php: {  }

build:
    environment:
        php:
            version: 8.0

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --config test/phpunit.xml'
                coverage:
                    file: 'test/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage: false
    php_code_coverage: true
    php_sim: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
