language: php
php:
  - '7.1'

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --configuration ./test/phpunit.xml

after_script:
  - travis_retry php ./vendor/bin/test-reporter --coverage-report=test/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/clover.xml
