language: php
php:
  - '5.6'
  - '7.0'

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --configuration ./test/phpunit.xml

after_script:
  - travis_retry php ./vendor/bin/test-reporter --coverage-report=/test/clover.xml